const { HumanMessage, SystemMessage } = require("@langchain/core/messages");
const { StateGraph, Annotation, START, END } = require("@langchain/langgraph");
const { getChatModel } = require("./agentes/modelFactory");
const mcpService = require("./McpService");

// --- 1. SHARED STATE SCHEMA ---
const AgentState = Annotation.Root({
  // Global Input
  task: Annotation(),           // User's original query
  
  // Pipeline Artifacts
  sql_query: Annotation(),      // Generated by SQL Intelligence
  raw_data: Annotation(),       // Result from Data Retrieval
  analysis_result: Annotation(),// Stats from Data Scientist
  anomaly_insights: Annotation(),// Anomaly detection results
  vega_lite_spec: Annotation(), // Visualization logic
  dashboard_spec: Annotation(), // Final dashboard layout
  
  // System Metadata
  messages: Annotation(),       // Conversation history
  errors: Annotation(),         // Error tracking
  current_agent: Annotation()   // Traceability
});

// --- 2. AGENT DEFINITIONS (Placeholders for now) ---

// --- 2. AGENT DEFINITIONS ---

const sqlIntelligenceAgent = async (state) => {
    console.error("[DEBUG_SQL] sqlIntelligenceAgent STARTED");
    console.error("[DEBUG_SQL] Analyzing task:", state.task);
    const { task } = state;
    
    // We reuse the logic from the previous SQL Agent but strictly for SQL generation
    const tool = mcpService.getTool("query_db"); // We use the schema from query_db tool to inform the LLM
    
    const prompt = `Eres un Agente SQL Industrial.
    TU OBJETIVO: Generar una consulta SQL SELECT válida y optimizada basada en la solicitud del usuario.
    
    ESQUEMA DE BASE DE DATOS:
    ${require("../constants/schema").DB_SCHEMA}
    
    REGLAS ESTRICTAS DE SQL:
    1. Solo genera la consulta SQL. NADA de texto adicional.
    2. Usa la tabla 'datos' para los registros de sensores.
    3. La columna de voltaje/promedio es 'mean' (NUMERIC). NO uses 'valor'.
    4. El nombre del dispositivo está en devices.name. NO uses devices.planta.
    5. Une tablas con: datos.device_uid = devices.device_uid.
    6. Trae datos crudos (SELECT *) y deja que el DATA_SCIENTIST los procese.
    7. Usa LIMIT 50 por defecto si no se pide una cantidad específica.
    8. Devuelve un JSON: { "sql": "SELECT ..." }
    
    SOLICITUD: ${task}
    `;

    try {
        const model = getChatModel({ temperature: 0 });
        const response = await model.invoke([new HumanMessage(prompt)]);
        let sql = response.content.replace(/```json/g, "").replace(/```/g, "").trim();
        
        // Try parsing JSON if model wrapped it
        try {
            const parsed = JSON.parse(sql);
            if (parsed.sql) sql = parsed.sql;
        } catch(e) {}
        
        console.error("[DEBUG_SQL] Generated SQL:", sql);
        return { sql_query: sql, current_agent: "sql_intelligence" };
    } catch (error) {
        console.error("   ❌ SQL Gen Failed:", error);
        return { errors: [`SQL Gen: ${error.message}`] };
    }
};

const dataRetrievalAgent = async (state) => {
    console.log("➡️ [Data Retrieval] Executing SQL...");
    const { sql_query } = state;
    
    if (!sql_query) {
        return { errors: ["No SQL query generated"], current_agent: "data_retrieval" };
    }

    try {
        // We use the existing tool execution logic but directly
        // The tool 'query_db' usually expects { query: "..." }
        // We can simulate tool execution or call the service directly if exposed.
        // For now, let's assume we can use mcpService to find the tool func or simply reuse the connection logic.
        // Since McpService wraps tools, we might need a direct DB accessor or use the tool via string.
        
        // Simulating direct DB call via the existing tool function referenced in mcpService
        // In a real implementation we would import the db connector.
        // For expediency, we'll try to use the Tool interface if available, or assume a direct require.
        
        // Ideally: const db = require('../db/client'); const res = await db.query(sql_query);
        // Let's rely on the mcpService tool 'query_db' which is available.
        const dbTool = mcpService.getTool("query_db");
        if (!dbTool) throw new Error("Database tool not found");
        
        const toolResult = await dbTool.func({ sql: sql_query });
        let rows = [];
        try {
             const content = toolResult.content[0];
             const jsonString = content.text;
             
             // DEBUG LOG to identify why it's "[object Object]"
             console.log("➡️ [Data Retrieval] Content type:", typeof jsonString);

             const parsed = typeof jsonString === 'string' ? JSON.parse(jsonString) : jsonString;
             
             if (parsed.status === "error") {
                 console.error("   ❌ Tool Error:", parsed.metadata?.error || "Unknown error");
                 return { errors: [parsed.metadata?.error || "DB Error"], current_agent: "data_retrieval" };
             }

             rows = parsed.data?.rows || parsed.data || [];
        } catch(e) {
             console.warn("   ⚠️ Could not parse DB result as JSON:", e.message);
             rows = []; 
        }

        console.log(`   ✅ Retrieved ${rows.length} rows.`);
        return { raw_data: rows, current_agent: "data_retrieval" };

    } catch (error) {
        console.error("   ❌ Execution Failed:", error);
        return { errors: [`DB Exec: ${error.message}`] };
    }
};

const autonomousDataScientist = async (state) => {
    console.log("➡️ [Data Scientist] Analyzing data...");
    const { raw_data, task } = state;

    if (!raw_data || raw_data.length === 0) {
        return { errors: ["No data to analyze"], current_agent: "data_scientist" };
    }

    try {
        const rowCount = raw_data.length;
        const columns = Object.keys(raw_data[0] || {});
        const hasNumericColumns = columns.some(c => c === 'mean' || c === 'valor' || c === 'voltaje');
        
        // --- STEP 1: Decide Decision (Danfo vs Mental) ---
        // If dataset has numeric columns and more than 20 rows, it should use Danfo
        const useDanfo = rowCount > 20 && hasNumericColumns;

        let finalAnalysis = null;

        if (useDanfo) {
            console.log(`   🧮 Using Danfo.js for mathematical analysis (${rowCount} rows)...`);
            
            // --- STEP 2: Generate Danfo Execution Code ---
            const codeGenPrompt = `Eres un Científico de Datos experto en Danfo.js. 
            Genera código JavaScript usando Danfo para analizar el dataset. 
            
            ESQUEMA: ${columns.join(", ")}
            TAREA: ${task}
            
            REGLAS:
            1. El código debe usar la variable 'df' (Dataframe ya disponible).
            2. NO declares 'dfd' ni uses 'require'. Las variables 'df', 'dfd' y 'helpers' YA están disponibles en el ámbito global.
            3. LOS DATOS YA VIENEN FILTRADOS por el Agente SQL. NO intentes filtrar por 'name' o 'planta' de nuevo a menos que sea estrictamente necesario.
            4. IMPORTANTE: Las columnas numéricas (como 'mean') suelen venir como string. Usa df['mean'].asType('float32') antes de calcular estadísticas.
            5. Debe calcular estadísticas clave (promedio, máximo, mínimo, desviación estándar).
            6. El código DEBE RETORNAR un objeto plano al final: return { ... }.
            7. NO uses .plot() ni nodeplotlib.
            
            CÓDIGO (Devuelve solo el código JS):`;

            const model = getChatModel({ temperature: 0 });
            const codeResponse = await model.invoke([new HumanMessage(codeGenPrompt)]);
            const code = codeResponse.content.replace(/```javascript/g, "").replace(/```/g, "").trim();

            // --- STEP 3: Execute Tool ---
            const result = await mcpService.runTool("analizar_datos_locales", {
                datos: raw_data,
                codigo: code
            });

            if (!result.ok || !result.parsed || result.parsed.status === "error") {
                console.warn("   ⚠️ Danfo Execution failed:", result.parsed?.metadata?.error || "Unknown error");
                console.warn("   ⚠️ Falling back to mental analysis");
            } else {
                const mathResults = result.parsed.data || result.parsed.result;
                console.log("   ✅ Mathematical results obtained.");

                // --- STEP 4: Summarize Results ---
                const summaryPrompt = `Eres un Científico de Datos. Resume estos resultados matemáticos para el usuario.
                
                RESULTADOS: ${JSON.stringify(mathResults)}
                TAREA: ${task}
                
                FORMATO JSON EXIGIDO:
                {
                  "resumen": "Interpretación experta de los datos",
                  "metrias": [ { "label": "Nombre", "value": "valor", "status": "ok|warning|danger" }, ... ],
                  "source": "danfo_analysis"
                }`;
                
                const summaryResponse = await model.invoke([new HumanMessage(summaryPrompt)]);
                try {
                    const text = summaryResponse.content.replace(/```json/g, "").replace(/```/g, "").trim();
                    finalAnalysis = JSON.parse(text);
                } catch(e) {
                    finalAnalysis = { resumen: summaryResponse.content, metrias: [], source: "danfo_analysis" };
                }
            }
        }

        // --- FALLBACK: Mental Analysis (If not using Danfo or tool failed) ---
        if (!finalAnalysis) {
            console.log("   🧠 Performing mental statistical estimation...");
            const prompt = `Eres un Científico de Datos Autónomo.
            Analiza el dataset proporcionado (basado en muestra) y extrae estadísticas estimadas.
            
            DATASET MUESTRA: ${JSON.stringify((raw_data || []).slice(0, 5))}
            TOTAL FILAS: ${rowCount}
            TAREA: ${task}
            
            FORMATO JSON:
            {
              "resumen": "Texto con conclusiones",
              "metrias": [ { "label": "Nombre", "value": "valor", "status": "ok|warning|danger" }, ... ],
              "source": "mental_estimation"
            }`;

            const model = getChatModel({ temperature: 0 });
            const response = await model.invoke([new HumanMessage(prompt)]);
            try {
                 const text = response.content.replace(/```json/g, "").replace(/```/g, "").trim();
                 finalAnalysis = JSON.parse(text);
            } catch(e) {
                 finalAnalysis = { resumen: response.content, metrias: [], source: "mental_estimation" };
            }
        }

        console.log(`   ✅ Analysis complete (Source: ${finalAnalysis.source}).`);
        return { analysis_result: finalAnalysis, current_agent: "data_scientist" };

    } catch (error) {
        console.error("   ❌ Analysis Failed:", error);
        return { errors: [`Analysis: ${error.message}`] };
    }
};

const anomalyDetectionAgent = async (state) => {
    console.log("➡️ [Anomaly Detector] Checking for outliers...");
    const { raw_data, analysis_result } = state;
    
    // Simple statistical anomaly detection (Z-Score approximation or based on LLM insight)
    // For this MVP, we ask the LLM to identify potential outliers based on the summary and data sample
    
    const prompt = `Eres un Detector de Anomalías Industrial.
    Analiza la muestra de datos y las estadísticas previas para encontrar valores fuera de rango.
    
    ESTADÍSTICAS: ${JSON.stringify(analysis_result || {})} (Contiene resumen y metrias)
    MUESTRA DATOS: ${JSON.stringify((raw_data || []).slice(0, 20))}
    
    JSON SALIDA:
    {
      "detected": boolean,
      "reason": "Texto explicando por qué",
      "count": number
    }
    `;
    
    try {
        const model = getChatModel({ temperature: 0 });
        const response = await model.invoke([new HumanMessage(prompt)]);
        let insights = {};
        try {
             const text = response.content.replace(/```json/g, "").replace(/```/g, "").trim();
             insights = JSON.parse(text);
        } catch(e) {
             insights = { detected: false, reason: "Parse error" };
        }

        console.log(`   ✅ Anomaly check: ${insights.detected ? "FOUND" : "Clear"}`);
        return { anomaly_insights: insights, current_agent: "anomaly_detector" };

    } catch (error) {
         console.warn("   ⚠️ Anomaly Detection Failed", error);
         return { anomaly_insights: { error: true }, current_agent: "anomaly_detector" };
    }
};

const visualizationIntelligenceAgent = async (state) => {
    console.log("➡️ [Vis Intelligence] Designing charts...");
    const { raw_data, analysis_result, anomaly_insights } = state;
    
    // Construct Vega-Lite Spec
    const prompt = `Eres un Experto en Visualización de Datos (Vega-Lite).
    Genera un JSON de Vega-Lite válido para visualizar estos datos.
    
    CONTEXTO:
    - Datos: ${raw_data?.length || 0} filas.
    - Campos: ${Object.keys((raw_data && raw_data[0]) || {}).join(", ")}
    - Análisis: ${JSON.stringify(analysis_result || {})} (Usa resumen y metrias)
    - Anomalías: ${JSON.stringify(anomaly_insights || {})}
    
    REGLAS:
    1. Usa SIEMPRE "data": { "values": [...] } e INCLUYE LOS DATOS (máximo 50 puntos para gráficas ligeras, o todos si son pocos).
    2. Si hay campo de tiempo (created_at, timestamp), úsalo en el eje X.
    3. Si hay anomalías, resáltalas en rojo.
    4. Devuelve SOLO el JSON. NADA de texto explicativo ni antes ni después.
    5. Si no hay datos, genera un gráfico vacío pero válido sintácticamente.
    
    JSON VEGA-LITE (SIN TEXTO EXTRA):
    `;
    
    try {
        const model = getChatModel({ temperature: 0 });
        const response = await model.invoke([new HumanMessage(prompt)]);
        let spec = null;
        try {
            // Robust Parsing: Extract JSON object from potential markdown or text
            const text = response.content;
            const first = text.indexOf('{');
            const last = text.lastIndexOf('}');
            
            if (first !== -1 && last !== -1) {
                const jsonText = text.substring(first, last + 1);
                spec = JSON.parse(jsonText);
            } else {
                throw new Error("No JSON object found in response");
            }
            
             // Ensure data.values is populated
             if (!spec.data || !spec.data.values || spec.data.values.length === 0) {
                 spec.data = { values: (raw_data || []).slice(0, 100) }; 
             }
             
             return { vega_lite_spec: spec, current_agent: "visualization_intelligence" };

        } catch (e) {
            console.warn("   ⚠️ Vega-Lite Parse Error", e);
            console.warn("   ⚠️ Raw Response:", response.content);
        }

        return { vega_lite_spec: null, current_agent: "visualization_intelligence" };

    } catch (error) {
        console.error("   ❌ Vis Gen Failed:", error);
        return { errors: [`Vis Gen: ${error.message}`] };
    }
};

const dashboardOrchestrationAgent = async (state) => {
    console.log("➡️ [Dashboard Orchestrator] Assembling response...");
    const { analysis_result, anomaly_insights, vega_lite_spec } = state;
    
    // Combine everything into a structured dashboard object
    // For this MVP, we return a structure compatible with the frontend expectations
    
    const dashboard = {
        title: "Industrial AI Dashboard",
        resumen: analysis_result?.resumen || "Análisis completado.",
        metrias: analysis_result?.metrias || [],
        anomalies: anomaly_insights,
        source: analysis_result?.source || "unknown",
        charts: vega_lite_spec ? [{ title: "Tendencia del Proceso", spec: vega_lite_spec }] : []
    };

    console.log("   ✅ Dashboard ready.");
    return { dashboard_spec: dashboard, current_agent: "dashboard_orchestrator" };
};

// --- 3. GRAPH CONSTRUCTION ---

const workflow = new StateGraph(AgentState)
    .addNode("sql_intelligence", sqlIntelligenceAgent)
    .addNode("data_retrieval", dataRetrievalAgent)
    .addNode("data_scientist", autonomousDataScientist)
    .addNode("anomaly_detector", anomalyDetectionAgent)
    .addNode("visualization_intelligence", visualizationIntelligenceAgent)
    .addNode("dashboard_orchestrator", dashboardOrchestrationAgent)

    // Sequential Flow
    .addEdge(START, "sql_intelligence")
    .addEdge("sql_intelligence", "data_retrieval")
    .addEdge("data_retrieval", "data_scientist")
    .addEdge("data_scientist", "anomaly_detector")
    .addEdge("anomaly_detector", "visualization_intelligence")
    .addEdge("visualization_intelligence", "dashboard_orchestrator")
    .addEdge("dashboard_orchestrator", END);

// Compile
const app = workflow.compile();

module.exports = app;
