const { HumanMessage, SystemMessage } = require("@langchain/core/messages");
const { StateGraph, Annotation, START, END } = require("@langchain/langgraph");
const { getChatModel } = require("./agentes/modelFactory");
const mcpService = require("./McpService");

// --- 1. SHARED STATE SCHEMA ---
const AgentState = Annotation.Root({
  // Global Input
  task: Annotation(),           // User's original query
  
  // Pipeline Artifacts
  sql_query: Annotation(),      // Generated by SQL Intelligence
  raw_data: Annotation(),       // Result from Data Retrieval
  analysis_result: Annotation(),// Stats from Data Scientist
  anomaly_insights: Annotation(),// Anomaly detection results
  vega_lite_spec: Annotation(), // Visualization logic
  dashboard_spec: Annotation(), // Final dashboard layout
  
  // System Metadata
  messages: Annotation(),       // Conversation history
  errors: Annotation(),         // Error tracking
  current_agent: Annotation()   // Traceability
});

// --- 2. AGENT DEFINITIONS (Placeholders for now) ---

// --- 2. AGENT DEFINITIONS ---

const sqlIntelligenceAgent = async (state) => {
    console.error("[DEBUG_SQL] sqlIntelligenceAgent STARTED");
    console.error("[DEBUG_SQL] Analyzing task:", state.task);
    const { task } = state;
    
    const prompt = `Eres un Experto en SQL para un sistema de manufactura.
    Genera una consulta SQL para PostgreSQL basada en la tarea del usuario.
    
    TABLAS DISPONIBLES:
    - datos: id, device_uid, mean, created_at
    - devices: id, device_uid, name, description
    
    REGLAS ESTRICTAS:
    1. Devuelve SOLAMENTE el código SQL plano.
    2. NO uses bloques de Markdown (sin \`\`\`sql).
    3. NO incluyas explicaciones ni comentarios.
    4. Usa JOIN entre "datos" y "devices" usando "device_uid".
    5. ROBUSTEZ: Si piden un rango de tiempo, usa UNION con los últimos 5 registros para asegurar que el usuario vea datos si el rango está vacío.
    6. Siempre añade LIMIT 100.
    
    TAREA: ${task}
    SQL:`;

    try {
        const model = getChatModel({ temperature: 0 });
        const response = await model.invoke([new HumanMessage(prompt)]);
        let sql = response.content.replace(/```json/g, "").replace(/```/g, "").trim();
        
        // Try parsing JSON if model wrapped it
        try {
            const parsed = JSON.parse(sql);
            if (parsed.sql) sql = parsed.sql;
        } catch(e) {}
        
        console.error("[DEBUG_SQL] Generated SQL:", sql);
        return { sql_query: sql, current_agent: "sql_intelligence" };
    } catch (error) {
        console.error("   ❌ SQL Gen Failed:", error);
        return { errors: [`SQL Gen: ${error.message}`] };
    }
};

const dataRetrievalAgent = async (state) => {
    console.log("➡️ [Data Retrieval] Executing SQL...");
    const { sql_query } = state;
    
    if (!sql_query) {
        return { errors: ["No SQL query generated"], current_agent: "data_retrieval" };
    }

    try {
        // We use the existing tool execution logic but directly
        // The tool 'query_db' usually expects { query: "..." }
        // We can simulate tool execution or call the service directly if exposed.
        // For now, let's assume we can use mcpService to find the tool func or simply reuse the connection logic.
        // Since McpService wraps tools, we might need a direct DB accessor or use the tool via string.
        
        // Simulating direct DB call via the existing tool function referenced in mcpService
        // In a real implementation we would import the db connector.
        // For expediency, we'll try to use the Tool interface if available, or assume a direct require.
        
        // Ideally: const db = require('../db/client'); const res = await db.query(sql_query);
        // Let's rely on the mcpService tool 'query_db' which is available.
        const dbTool = mcpService.getTool("query_db");
        if (!dbTool) throw new Error("Database tool not found");
        
        const toolResult = await dbTool.func({ sql: sql_query });
        let rows = [];
        try {
             const content = toolResult.content[0];
             const jsonString = content.text;
             
             // DEBUG LOG to identify why it's "[object Object]"
             console.log("➡️ [Data Retrieval] Content type:", typeof jsonString);

             const parsed = typeof jsonString === 'string' ? JSON.parse(jsonString) : jsonString;
             
             if (parsed.status === "error") {
                 console.error("   ❌ Tool Error:", parsed.metadata?.error || "Unknown error");
                 return { errors: [parsed.metadata?.error || "DB Error"], current_agent: "data_retrieval" };
             }

             rows = parsed.data?.rows || parsed.data || [];
        } catch(e) {
             console.warn("   ⚠️ Could not parse DB result as JSON:", e.message);
             rows = []; 
        }

        console.log(`   ✅ Retrieved ${rows.length} rows.`);
        return { raw_data: rows, current_agent: "data_retrieval" };

    } catch (error) {
        console.error("   ❌ Execution Failed:", error);
        return { errors: [`DB Exec: ${error.message}`] };
    }
};

const autonomousDataScientist = async (state) => {
    console.log("➡️ [Data Scientist] ENTERPRISE MODE: Starting 6-Phase Analysis...");
    const { raw_data, task } = state;

    if (!raw_data || raw_data.length === 0) {
        console.warn("   ⚠️ No data received for analysis.");
        return { 
            analysis_result: { 
                source: "robustness_fallback",
                resumen: "No se encontraron datos en el rango de tiempo o dispositivo seleccionado. Por favor, verifica si la planta está activa o intenta con un rango más amplio.",
                metrias: [],
                root_cause: "La consulta a la base de datos devolvió 0 resultados."
            }, 
            current_agent: "data_scientist" 
        };
    }

    try {
        const rowCount = raw_data.length;
        const latestTime = new Date(raw_data[0].created_at);
        const now = new Date();
        const diffMinutes = Math.abs(now - latestTime) / (1000 * 60);
        const isStale = diffMinutes > 30; // More than 30 mins old

        const columns = Object.keys(raw_data[0] || {});
        const hasNumericColumns = columns.some(c => c === 'mean' || c === 'valor' || c === 'voltaje' || c === 'resultado');
        
        // --- STEP 1: Decide Decision (Danfo vs Mental) ---
        // Industrial Enterprise Rule: Always use Danfo if rowCount > 10
        const useDanfo = rowCount > 10 && hasNumericColumns;

        let enterpriseResults = {
            source: "enterprise_autonomous_analysis",
            statistics: {},
            features: {},
            anomalies: { source: "statistical_detection", details: {} },
            trends: {},
            forecast: {},
            root_cause: ""
        };

        if (useDanfo) {
            console.log(`   🧮 Phase 1-5: Executing mathematical pipeline (${rowCount} rows)...`);
            
            // --- STEP 2: Generate Comprehensive Danfo Code ---
            const codeGenPrompt = `Eres un Científico de Datos Industrial experto en Danfo.js. 
            Genera un script robusto para analizar este dataset en 5 fases matemáticas.
            
            ESQUEMA: ${columns.join(", ")}
            TAREA: ${task}
            
            REGLAS TÉCNICAS (ESTRICTAS):
            1. Devuelve SOLAMENTE el código JavaScript ejecutable. NO incluyas explicaciones.
            2. Usa 'df' (Dataframe ya disponible). 'dfd' y 'helpers' también están disponibles.
            3. NO declares 'dfd' ni uses 'require'.
            4. IMPORTANTE: No uses df['col'] = series para asignar. Usa: const newDf = df.addColumn('name', series) o trabaja con Series independientes.
            5. Convierte columnas numéricas (ej: 'mean') con df['mean'].asType('float32').
            6. PROHIBIDO: No uses .plot(), ni helpers.plot, ni ninguna función de graficación. Devuelve solo DATOS.
            
            PLANTILLA SUGERIDA (Sigue esta lógica):
            const col = df['mean'].asType('float32');
            const stats = { mean: col.mean(), std: col.std(), max: col.max(), min: col.min() };
            const zscore = col.sub(stats.mean).div(stats.std).abs();
            const outliers = zscore.gt(3);
            const trend = helpers.regressionSlope(col.values);
            const forecast = helpers.movingAverage(col.values.slice(-10), 3);
            
            return {
                statistics: stats,
                features: { rolling_mean: helpers.movingAverage(col.values, 5) },
                anomalies: { count: col.values.filter((_,i) => zscore.values[i] > 3).length, details: [] },
                trends: { slope: trend },
                forecast: { next: forecast.slice(-5), confidence: "medium" }
            };`;

            const model = getChatModel({ temperature: 0 });
            const codeResponse = await model.invoke([new HumanMessage(codeGenPrompt)]);
            
            // Robust extraction: find the code between blocks or the whole content
            let code = codeResponse.content;
            if (code.includes("```")) {
                const parts = code.split("```");
                code = parts[1];
                if (code.startsWith("javascript")) code = code.replace("javascript", "");
                if (code.startsWith("js")) code = code.replace("js", "");
            }
            code = code.trim();

            console.log("   📜 FULL GENERATED CODE:\n" + "=".repeat(40) + "\n" + code + "\n" + "=".repeat(40));

            const result = await mcpService.runTool("analizar_datos_locales", {
                datos: raw_data,
                codigo: code
            });

            if (result.ok && result.parsed && result.parsed.status !== "error") {
                const math = result.parsed.data || result.parsed.result;
                Object.assign(enterpriseResults, math);
                console.log("   ✅ Mathematical pipeline complete.");
            } else {
                console.warn("   ⚠️ Math failed, using fallback summary", result.parsed?.metadata?.error);
            }
        }

        // --- STEP 3: Phase 6 - Root Cause Analysis & Human Summary ---
        console.log("   🧪 Phase 6: Generating Root Cause Analysis & Insights...");
        const summaryPrompt = `Eres un Experto en Inteligencia Industrial. 
        Analiza los resultados matemáticos y genera un informe de nivel "Enterprise".
        
        DATOS MATEMÁTICOS: ${JSON.stringify(enterpriseResults)}
        TAREA ORIGINAL: ${task}
        MUESTRA DATOS: ${JSON.stringify(raw_data.slice(0, 3))}
        
        OBJETIVO:
        1. Explica la "Causa Raíz" (Root Cause) de las tendencias o anomalías detectadas.
        2. Proporciona un resumen ejecutivo de alto nivel.
        3. Formatea las métricas para que sean legibles.
        
        FORMATO JSON EXIGIDO:
        {
          "resumen": "Resumen ejecutivo con hallazgos clave",
          "metrias": [ { "label": "Nombre", "value": "valor", "status": "ok|warning|danger" }, ... ],
          "root_cause": "Explicación técnica de la causa raíz",
          "source": "enterprise_autonomous_analysis"
        }`;
        
        const model = getChatModel({ temperature: 0 });
        const summaryResponse = await model.invoke([new HumanMessage(summaryPrompt)]);
        
        try {
            const parsed = JSON.parse(summaryResponse.content.replace(/```json/g, "").replace(/```/g, "").trim());
            Object.assign(enterpriseResults, parsed);
        } catch(e) {
            enterpriseResults.resumen = summaryResponse.content;
            enterpriseResults.root_cause = "Error al parsear RCA avanzado.";
        }

        if (isStale) {
            enterpriseResults.resumen = `⚠️ **Nota: Los datos mostrados tienen una antigüedad de ${Math.round(diffMinutes)} minutos.**\n\n` + (enterpriseResults.resumen || "");
        }

        console.log(`   ✅ Enterprise Analysis Complete.`);
        return { analysis_result: enterpriseResults, current_agent: "data_scientist" };

    } catch (error) {
        console.error("   ❌ Enterprise Analysis Failed:", error);
        return { errors: [`Enterprise DS: ${error.message}`] };
    }
};

const anomalyDetectionAgent = async (state) => {
    console.log("➡️ [Anomaly Detector] Checking for outliers...");
    const { raw_data, analysis_result } = state;
    
    // Simple statistical anomaly detection (Z-Score approximation or based on LLM insight)
    // For this MVP, we ask the LLM to identify potential outliers based on the summary and data sample
    
    const prompt = `Eres un Detector de Anomalías Industrial.
    Analiza la muestra de datos y las estadísticas previas para encontrar valores fuera de rango.
    
    ESTADÍSTICAS: ${JSON.stringify(analysis_result || {})} (Contiene resumen y metrias)
    MUESTRA DATOS: ${JSON.stringify((raw_data || []).slice(0, 20))}
    
    JSON SALIDA:
    {
      "detected": boolean,
      "reason": "Texto explicando por qué",
      "count": number
    }
    `;
    
    try {
        const model = getChatModel({ temperature: 0 });
        const response = await model.invoke([new HumanMessage(prompt)]);
        let insights = {};
        try {
             const text = response.content.replace(/```json/g, "").replace(/```/g, "").trim();
             insights = JSON.parse(text);
        } catch(e) {
             insights = { detected: false, reason: "Parse error" };
        }

        console.log(`   ✅ Anomaly check: ${insights.detected ? "FOUND" : "Clear"}`);
        return { anomaly_insights: insights, current_agent: "anomaly_detector" };

    } catch (error) {
         console.warn("   ⚠️ Anomaly Detection Failed", error);
         return { anomaly_insights: { error: true }, current_agent: "anomaly_detector" };
    }
};

const visualizationIntelligenceAgent = async (state) => {
    console.log("➡️ [Vis Intelligence] Designing charts...");
    const { raw_data, analysis_result, anomaly_insights } = state;
    
    if (!raw_data || raw_data.length === 0) {
        console.warn("   ⚠️ Skipping chart: No data available.");
        return { vega_lite_spec: null, current_agent: "visualization_intelligence" };
    }

    // Construct Vega-Lite Spec
    const prompt = `Eres un Experto en Visualización de Datos (Vega-Lite).
    Genera un JSON de Vega-Lite válido para visualizar los resultados analíticos industriales.
    
    CONTEXTO ENTERPRISE:
    - Datos: ${raw_data?.length || 0} registros.
    - Campos: ${Object.keys((raw_data && raw_data[0]) || {}).join(", ")}
    - Análisis: ${JSON.stringify(analysis_result || {})} 
    - Anomalías: ${JSON.stringify(anomaly_insights || {})}
    
    REGLAS DE DISEÑO:
    1. Usa SIEMPRE "data": { "values": [...] }. 
    2. IMPORTANTE: El JSON debe ser 100% VÁLIDO. NO uses comentarios (// ...) ni puntos suspensivos dentro del JSON. Si hay muchos datos, incluye solo los primeros 50 elementos reales.
    3. Si hay "forecast" (predicción), añádela al gráfico.
    3. Si hay "features" (como rolling_mean), graba una segunda línea para mostrar la tendencia suavizada.
    4. Usa colores industriales (azul para datos, naranja para tendencias, rojo para anomalías).
    5. Devuelve SOLO el objeto JSON. Sin Markdown, sin texto explicativo.
    
    JSON VEGA-LITE:`;
    
    try {
        const model = getChatModel({ temperature: 0 });
        const response = await model.invoke([new HumanMessage(prompt)]);
        
        console.log("   📊 [Vis Gen] LLM Response received (first 100 chars):", response.content.substring(0, 100) + "...");
        
        let spec = null;
        try {
            // Robust Parsing: Extract JSON object from potential markdown or text
            const text = response.content;
            const first = text.indexOf('{');
            const last = text.lastIndexOf('}');
            
            if (first !== -1 && last !== -1) {
                const jsonText = text.substring(first, last + 1);
                spec = JSON.parse(jsonText);
            } else {
                throw new Error("No JSON object found in response");
            }
            
             // Ensure data.values is populated
             if (!spec.data || !spec.data.values || spec.data.values.length === 0) {
                 spec.data = { values: (raw_data || []).slice(0, 100) }; 
             }
             
             return { vega_lite_spec: spec, current_agent: "visualization_intelligence" };

        } catch (e) {
            console.warn("   ⚠️ Vega-Lite Parse Error", e);
            console.warn("   ⚠️ Raw Response:", response.content);
        }

        return { vega_lite_spec: null, current_agent: "visualization_intelligence" };

    } catch (error) {
        console.error("   ❌ Vis Gen Failed:", error);
        return { errors: [`Vis Gen: ${error.message}`] };
    }
};

const dashboardOrchestrationAgent = async (state) => {
    console.log("➡️ [Dashboard Orchestrator] Assembling response...");
    const { analysis_result, anomaly_insights, vega_lite_spec } = state;
    
    // Combine everything into a structured dashboard object
    // For this MVP, we return a structure compatible with the frontend expectations
    
    const dashboard = {
        title: "Industrial AI Dashboard",
        resumen: analysis_result?.resumen || "Análisis completado.",
        metrias: analysis_result?.metrias || [],
        anomalies: analysis_result?.anomalies || anomaly_insights, // Prefer statistical anomalies
        source: analysis_result?.source || "unknown",
        root_cause: analysis_result?.root_cause || "",
        statistics: analysis_result?.statistics || {},
        features: analysis_result?.features || {},
        trends: analysis_result?.trends || {},
        forecast: analysis_result?.forecast || {},
        charts: vega_lite_spec ? [{ title: "Tendencia del Proceso", spec: vega_lite_spec }] : []
    };

    console.log("   ✅ Dashboard ready.");
    return { dashboard_spec: dashboard, current_agent: "dashboard_orchestrator" };
};

// --- 3. GRAPH CONSTRUCTION ---

const workflow = new StateGraph(AgentState)
    .addNode("sql_intelligence", sqlIntelligenceAgent)
    .addNode("data_retrieval", dataRetrievalAgent)
    .addNode("data_scientist", autonomousDataScientist)
    .addNode("anomaly_detector", anomalyDetectionAgent)
    .addNode("visualization_intelligence", visualizationIntelligenceAgent)
    .addNode("dashboard_orchestrator", dashboardOrchestrationAgent)

    // Sequential Flow
    .addEdge(START, "sql_intelligence")
    .addEdge("sql_intelligence", "data_retrieval")
    .addEdge("data_retrieval", "data_scientist")
    .addEdge("data_scientist", "anomaly_detector")
    .addEdge("anomaly_detector", "visualization_intelligence")
    .addEdge("visualization_intelligence", "dashboard_orchestrator")
    .addEdge("dashboard_orchestrator", END);

// Compile
const app = workflow.compile();

module.exports = app;
